# Generated by Django 4.0.1 on 2022-01-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='upload',
            name='image2',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
